### ISSUE TITLE
Árboles o Hash table 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#11]

**Comment by Tyrone-J** [comment]
Arboles good 
Hash table zzzz

**Comment by Tyrone-J** [comment]
Decidimos usar arboles debido a que estamos mas acostumbrados a su uso y funciono exitosamente 🤑

**Comment by SebastianOsorio20** [comment]
optamos por arboles al ser una manera mas fácil de indexar nuestro trabajo

**Comment by MarlonLLaguento** [comment]
Elegimos árboles por que nos permite utilizar menos espacios, además que el tiempo de búsqueda es aceptable.
