### ISSUE TITLE
Testeo del programa 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#12]

**Comment by Tyrone-J** [comment]
Tras varias revisiones hechas al programa, este logro funcionar exitosamente 👍

**Comment by SebastianOsorio20** [comment]
Tras varios intentos , se logro detectar algunos errores dejándonos el programa de manera funcional

**Comment by MarlonLLaguento** [comment]
Se realizaron diversas pruebas para verificar el correcto funcionamiento de nuestro código, las cuales resultaron exitosas.
