### ISSUE TITLE
Definición del Alcance del Proyecto

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#2]

**Comment by MarlonLLaguento** [comment]
Este proyecto tiene miras a ser usado con diferentes tipos de transacciones, como el envío de archivos encriptados. Además, es la base del funcionamiento del sistema blockchain, lo cual nos permite entender de mejor manera esta tecnología.

**Comment by SebastianOsorio20** [comment]
El proyecto tienes miras a convertirse en un modelo de Blockchain , pero sin llegar a transacciones reales

**Comment by Tyrone-J** [comment]
Este trabajo tiene como finalidad alcanzar un buen nivel para las implementaciones de datos, usando la menor notación de big O
