### ISSUE TITLE
Diagrama de Clases 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#3]

**Comment by MarlonLLaguento** [comment]
Se realizó el diagrama de clases en base a lo explicado en clase y tomando en cuanta la indexación con árboles binarios.

**Comment by SebastianOsorio20** [comment]
Se dialogo para quedar cuales serian las clases necesarias para la realización del proyecto

**Comment by Tyrone-J** [comment]
Se creo el diagrama de clases, dando la base para la realización del código, pensando en los futuros métodos y clases que se usaran.
