### ISSUE TITLE
Notación Big O

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#4]

**Comment by MarlonLLaguento** [comment]
Se realizó la notación big O de funciones que se encuentran en la lista doblemente enlazada como el insertar, mostrar por letra, etc.

**Comment by SebastianOsorio20** [comment]
Se seleccionó algunas funciones para la notación big0

**Comment by Tyrone-J** [comment]
Mediante el desarrollo del Big O, se considero las opciones mas optimas posibles para disminuirlas
