### ISSUE TITLE
Redacción del Informe

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#5]

**Comment by Tyrone-J** [comment]
Se redacto el informe en grupo un fin de semana, describiendo la los objetivos del curso y las estructura de datos a usar entre otras cosas

**Comment by MarlonLLaguento** [comment]
Se realizó el informe en base al objetivo del proyecto, las estructuras usadas y los tipos de datos abstractos.

**Comment by SebastianOsorio20** [comment]
Se redacto el informe en grupo , repartiéndonos  una sección del informe cada uno .
