### ISSUE TITLE
Creación del Menú

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#6]

**Comment by SebastianOsorio20** [comment]
Se elaboró un menú dinámico de manera ordenada

**Comment by MarlonLLaguento** [comment]
Tomamos en cuenta que la interfaz sea entendible para el usuario, para que así no se pierda en la ejecución del programa.

**Comment by Tyrone-Sotil** [comment]
yo la conoci en un taxi

**Comment by Tyrone-J** [comment]
El menu quedo bonito
