### ISSUE TITLE
Implementación de la clase árbol 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#7]

**Comment by SebastianOsorio20** [comment]
Se logro implementar la indexación del árbol además de la búsqueda por criterios

**Comment by Tyrone-J** [comment]
El arbol binario logro insertarce en orden mediante 3 criterios diferentes que escoge el usuario

**Comment by MarlonLLaguento** [comment]
Implementamos con éxito esta clase para realizar las búsquedas de usuario, las transacciones por usuario, etc.
