### ISSUE TITLE
Implementación de la clase ListaBloques

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/Trabajo_Final-#8]

**Comment by SebastianOsorio20** [comment]
Logramos implementar nuestro blockchain con indexación por arboles

**Comment by MarlonLLaguento** [comment]
Tomamos en cuenta una interfaz que sea entendible para el usuario, para que así no se pierda en la ejecución del programa.

**Comment by Tyrone-J** [comment]
Se logro exitosamente el block chain mediante listas dobles

**Comment by MarlonLLaguento** [comment]
El desarrollo de esta clase sirvió para enlazar los bloques que contenían los arreglos de transacciones y así formar la cadena de nuestra blockchain.
